default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["POSTGRES_USER"] || ENV["USER"] || 'postgres' %>
  database: <%= ENV["POSTGRES_DB"] || 'ticket-service_development' %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: <%= ENV["POSTGRES_HOST"] || 'localhost' %>
  pool: <%= ENV["POSTGRES_POOL"] || 5 %>
  port: <%= ENV["POSTGRES_PORT"] || 5432 %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
